apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymaven
  labels:
    app: mymaven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mymaven
  template:
    metadata:
      labels:
        app: mymaven
    spec:
      containers:
      - name: mymaven
        image: mymaven/sneha758:v1
        ports:
        - containerPort: 8080
