apiVersion: v1
kind: Service
metadata:
  labels:
    app: mymaven
  name: mymaven
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: mymaven
